### ISSUE TITLE
How about new release?

### ISSUE THREAD

**Issue by dlancer** [HaikuArchives/Pe#24]
Current version in Haiku nighties is 2.4.5-1,  with annoying bugs (especially broken key bindings), for beta 1 release I think this should be fixed.

**Comment by waddlesplash** [comment]
Right. Will add that to my TODO list...

**Comment by waddlesplash** [comment]
@humdingerb has done this now, this issue can be closed.

**Comment by humdingerb** [comment]
Be aware that I only updated the gcc2 package as the others fail to build via haikuporter.
