### ISSUE TITLE
Pe missing symbol from reworked BCollator API

### ISSUE THREAD

**Issue by OdinZa** [HaikuArchives/Pe#50]
In hrev51192, Pe complains about a symbol missing that I guess was private or deprectated:

~> /boot/system/apps/Pe/Pe
runtime_loader: /boot/system/apps/Pe/Pe: Could not resolve symbol 'Compare__C9BCollatorPCcT1Sc'
resolve symbol "Compare__C9BCollatorPCcT1Sc" returned: -2147478780
runtime_loader: /boot/system/apps/Pe/Pe: Troubles relocating: Symbol not found
~>

See: https://dev.haiku-os.org/ticket/13538

**Comment by moochris** [comment]
I reported and fixed that bug already...
https://github.com/HaikuArchives/Pe/commit/7f4ca18b106c50cfdb3a4b699cb43ec60ea32499

**Comment by waddlesplash** [comment]
Yeah, it just needs a rebuild now.

**Comment by OdinZa** [comment]
It just needs update package Pe in Hybrid "nightly images" Haiku.
