### ISSUE TITLE
Enhancement : try to build with Paladin if BeIDE is not found

### ISSUE THREAD

**Issue by Sylvain78** [HaikuArchives/Pe#71]
Source/Utils.cpp
line 161 :
```
if (be_roster->FindApp("application/x-mw-BeIDE", &ide))
THROW(("BeIDE was not found"));
```
We could try to find "application/x-vnd.dw-Paladin" as a fallback.

**Comment by humdingerb** [comment]
How time flies... just a decade ago.  :)

**Comment by X547** [comment]
It would be better to use some add-on for this functionality instead of hard-coding every possible IDE.
